version: '3.3'

volumes:
  pg_foodgram:
  static_value:
  media_value:

services:
  db_foodgram:
    image: postgres:13.0-alpine
    volumes:
      - pg_foodgram:/var/lib/postgresql/data/
    env_file:
      - .production.env

  backend:
    image: khamaran/foodgram_backend
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db_foodgram
    env_file:
      - .production.env
    restart: always

  frontend:
    image: khamaran/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db_foodgram

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend
    restart: always
